# Generated by Django 2.0.5 on 2018-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dose',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='dose_units',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='pharmacy',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='prescriber',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
