# Generated by Django 2.0.5 on 2018-07-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20180719_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pill_count',
            field=models.IntegerField(default=0),
        ),
    ]
